version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: manage
      MYSQL_PASSWORD: 123456789
      MYSQL_DATABASE: manage
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
    mysql_data: