spring:
  application:
      name: jenkins


  datasource:
    url: jdbc:mysql://database-1.c7yy6g2ggkhr.us-east-1.rds.amazonaws.com:13306/manage
    username: admin
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 9091
