# Workflow to build a Java project with Gradle and cache/restore dependencies for optimized workflow execution time.

name: Project Jenkins

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
#          gradle-version: 'latest'  # Use the latest Gradle version
          cache-enabled: true       # Enable caching for dependencies

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Submit dependency graph
        uses: gradle/actions/dependency-submission@v4  # Submit for Dependabot Alerts
